### ISSUE TITLE
Cannot use `@route()` decorator more than once

### ISSUE THREAD

**Issue by TheClockTwister** [TheClockTwister/Aeros#13]
```python
@app.route("/")
@app.route("/<path:path>")
async def home():
```

raises

```
Traceback (most recent call last):
  File "N:/Git/GitHub/Aeros/aeros/Request.py", line 88, in <module>
    async def home():
  File "N:\Git\GitHub\Aeros\aeros\WebServer.py", line 277, in new_route_decorator
    self.logger.critical(f'Endpoint function "{func.__name__}" for "{rule}" could not be routed: ' + str(e))
AttributeError: 'NoneType' object has no attribute '__name__'
```

**Comment by TheClockTwister** [comment]
Quart keeps track of endpoint functions via some ind of memory addres or hash. Since we were decorating each function again with the `EasyRequest` or `sync_to_async`, this caused trouble. Since these are gone now (b3fd68da1cb87051cbfbb1c927b9b23bff1413f2), we are good again...
